[settings]
# The max amount of collectibles that can be added into a battle.
max-ball-amount = 5

# Displays additional information for error handling.
debug = false

[attributes]
# Add attributes for collectibles here if you want to access them for abilities/effects.

# EXAMPLES:
# European = ["Poland"]
# South-American = ["Brazil"]
# Western-Hemisphere = ["Brazil", "Mexico"]


# Messages for automated and classic modes
# Variables: {a_owner} {d_owner} {a_name} {a_owner} {dmg}
[messages]
# Messages for automated and classic styles.
# KEYWORDS: {a_owner} {d_owner} {a_name} {a_owner} {dmg}

attack = [
    "{a_owner}'s {a_name} attacks {d_owner}'s {d_name} for {dmg} DMG!",
    "{a_name} uppercuts {d_name}, dealing {dmg} DMG!",
    "{a_owner}'s {a_name} slices {d_name}! ({dmg} DMG)",
    "{a_name} lands a solid blow on {d_name} for {dmg} DMG",
]

defeat = [
   "{a_name} has easily crushed {d_name}!",
    "{d_owner}'s {d_name} has fallen to {a_owner}'s {a_name}.",
    "{a_name} knocks out {d_name}!",
    "{d_name} has been defeated!",
]

dodge = [
    "{a_name} tries to land a blow, but {d_name} dodges!",
    "{d_owner}'s {d_name} evades {a_owner}'s {a_name} attack!",
    "{d_name} sidesteps the attack!",
]
    "{a_owner}'s {a_name} attacks {d_owner}'s {d_name} for {dmg} DMG!",
    "{a_name} uppercuts {d_name}, dealing {dmg} DMG!",
    "{a_owner}'s {a_name} slices {d_name}! ({dmg} DMG)",
    "{a_name} lands a solid blow on {d_name} for {dmg} DMG
]

defeat-messages = [
    "{a_name} has easily crushed {d_name}!",
    "{d_owner}'s {d_name} has fallen to {a_owner}'s {a_name}.",
    "{a_name} knocks out {d_name}!",
    "{d_name} has been defeated!",
]

dodge-messages = [
    "{a_name} tries to land a blow, but {d_name} dodges!",
    "{d_owner}'s {d_name} evades {a_owner}'s {a_name} attack!",
    "{d_name} sidesteps the attack!",
]

